ONSdigital/sdx-transform-cs

Dockerfile
Previous to this fix the contents of the transform directory were
being copied into the app directory. This fix copies the transform
directory to /app/transform.
=> Fix transform directory copy into container.

transform/templates/csv.tmpl, transform/transformers/ImageTransformer.py, transform/views/image_filters.py
**Changes**
Don't pass date objects to template to be evaluated via a filter. Instead return strings and pass to template as a dict.
Check that times rendered in the csv file are correct. (Previously the long format was reporting the wrong HH:MM:SS.
Anyone but @iwootten
=> Determine dates prior to template rendering

transform/settings.py
**Changes**
Enables the logging level to be set by an environment variable
Should work the same by default
Set environment variable to a valid logging level
Anyone but @elliott-jenkins
=> configurable logging level

transform/transformers/PDFTransformer.py
**Changes**
Format answers as paragraphs with default styling within table. Fixes #24.
Use as part of a compose setup and send a payload for 112 with a huge comment (add a data item with 146 or 147 q_code and a large string).
**Who worked on this**
@iwootten
=> Use same paragraph style for questions/answers

transform/surveys/023.0205.json
I have added a label to display comments' content in form 0205. The expected result can be seen in the following screenshot:
To test it:
- open sdx-console,
- load 023.0205.json survey,
- within the "Data to send" text area assign "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et mattis elit, porta blandit sapien." to the 146 key,
- click the Submit button,
- from the Receiver section click on the Images tab and open the most recent image.
=> Add label in order to render comments

CHANGELOG.md, tests/test_pck_transformer.py, transform/transformers/PCKTransformer.py
Add survey id as a key to the `form_ids` dictionary.
@tundish can you give this a look over to make sure it doesn't break anything else - you know this service much better than me!
=> Add survey id key to form_ids dict to support non unique form ids

.codecov.yml
Config isn't needed as codecov will use the default branch anyhow (and this config is out of date now repo uses `master` as default)
=> Remove unneeded codecov config

CHANGELOG.md, Makefile
Some dependent libraries don't have their dependencies pinned with hashes so the `--require-hashes` switch on `pip` fails
=> Remove require hashes from pip install

CHANGELOG.md, tests/test_image_transformer.py, transform/transformers/ImageTransformer.py
The index file time is stuck at 2nd Nov (the last prod deployment) this is due to the python gotcha default parameters are cached at definition time not re-evaluated on function call.
=> Fixing index file time

CHANGELOG.md, tests/test_mwss_transform.py, transform/transformers/mwss_transformer.py
MWSS is changing to route around the total gross pay breakdown questions when the total is zero. New q_codes will be present for each pay pattern if the total is zero and the breakdown questions have been routed around:
```
weekly - d50
fortnightly - d50f
monthly - d151
four weekly - d152
five weekly - d153
```
As the downstream systems require answers for the breakdown questions this pull request imputes zero values for these q_codes when the new q_codes are present.
If `d50` or `d50f` is present, `50`, `60`, `70` and `80` are imputed with zero
If `d151` is present, `151`, `171`, and `181` are imputed with zero
If `d152` is present, `152`, `172`, and `182` are imputed with zero
If `d153` is present, `153`, `173`, and `183` are imputed with zero
- Fire up console and test variations of …
=> Impute zero values for MWSS

tests/test_mbs_transformer.py, transform/transformers/mbs_transformer.py
> Q_code 110 should now be written to the pck as the value entered by the user, not 1
=> Potable water should now return value submitted not 1

tests/replies/009.0255.json, tests/test_mbs_transformer.py, transform/transformers/mbs_transformer.py
> This change introduces a mechanism for putting survey reporting period start and end dates in to a PCK file, even when a respondent does not explicitly enter them. The dates are taken from a submission's metadata if they aren't present in the data field.
=> Pass default dates downstream

CHANGELOG.md, transform/surveys/009.0167.json
The turnover question was missing from the image.  Adding this question to the survey will include it in the image, as even though the figure was provided, if it's not in this definition, it gets ignored.
=> Add turnover question for mbs survey 167

CHANGELOG.md, tests/test_pck_transformer.py, transform/surveys/019.0018.json, transform/surveys/019.0019.json, transform/surveys/019.0020.json, transform/transformers/pck_transformer.py
Adds the calculated total values for both acquisitions and proceeds from disposals into the PCK file.
This is needed by the business and downstream falls over if we don't.
Ensure the following are present in the PCK file:
- `q_code - 692 - Total value of all acquisitions questions.`
- `q_code - 693 - Total value of all disposals questions.`
- `q_code - 714 - Total value of all acquisitions questions for only machinery and equipments sections.`
- `q_code - 715 - Total value of all disposals questions for only machinery and equipments sections.`
- the value of `714` is the sum of all values of `q_codes` - `['688', '695', '703', '707', '709', '711']`
- the value of `715` is the sum of all values of `q_codes` - `['689', '696', '704', '708', '710', '712']`
- the value of `692` is the sum of …
=> Calculate values from submitted data for downstream

CHANGELOG.md, tests/test_pck_transformer.py, transform/transformers/pck_transformer.py
https://trello.com/c/QPdTO4B7/2366-qcas-replace-negative-values-with-9s
Starting with QCAS (but will apply to other surveys), downstream cannot handle negative values in the pck files.  The solution is to replace any negative number with a number containing all 9's of the same size.
Also in this PR is an additional unit test for preprocess_comments as there was 1 line that didn't have coverage.
=> QCAS replace negative values with 9s

tests/test_pck_transformer.py, transform/transformers/pck_transformer.py
> QCAS needs the total calculated from rounded figures so that the values will be correct. Currently we create the totals and then round.
=> Total QCAS Values after rounding

CHANGELOG.md, transform/transformers/cord/ecommerce_transformer.py
> Mapping of 416 didn't work as option value was incorrect compared to what is in [runner](https://github.com/ONSdigital/eq-survey-runner/blob/92885d97547eaae02b924658b4df5b0f7eb10b0d/data/en/ecommerce_0051.json#L1679)
=> Correct r3 option value

CHANGELOG.md, tests/test_e_commerce_transformer.py, transform/surveys/187.0051.json
> q-code r3 is not showing on image file as it's using the transformed q-codes rather than r3. This fixes that.
=> Ensure R3 is shown on image file

CHANGELOG.md, Dockerfile
When building the image from sdx-transform-cs, an error was occurring when trying to run `apt-get update`. The way to fix this was to add a line before it which will remove the jessie-updates from sources.list.
- The best way to test is to purge your docker and rebuild the images
=> Updating dockerfile

CHANGELOG.md, transform/__init__.py
Release 3.10.0
- Update Jinja to 2.10.1 to fix a security issue.
- Update Pillow and PyYAML versions
- Updated the dockerfile
- Used Python 3.5 inbuilt dictionary merging instead of merge_dicts
- [Y ] CHANGELOG.md updated? (if required)
=> Release 3.10.0

CHANGELOG.md, tests/test_pck_transformer.py, transform/surveys/017.0001.json, transform/surveys/017.0002.json, transform/surveys/017.0003.json, transform/surveys/017.0004.json, transform/surveys/017.0005.json, transform/surveys/017.0006.json, transform/surveys/017.0007.json, transform/surveys/017.0008.json, transform/surveys/017.0009.json, transform/surveys/017.0010.json, transform/surveys/017.0011.json, transform/surveys/017.0012.json, transform/surveys/017.0013.json, transform/surveys/017.0014.json, transform/surveys/017.0033.json, transform/surveys/017.0034.json, transform/surveys/017.0051.json, transform/surveys/017.0052.json, transform/surveys/017.0057.json, transform/surveys/017.0058.json, transform/surveys/017.0061.json, transform/surveys/017.0070.json, transform/transformers/common_software/pck_transformer.py
Stocks had its name changed from QSI to QSS.  This PR changes all references to the former with the latter.
=> Rename QSI to QSS

tests/pck/cord/187.0001.dependent_ecommerce_questions.json, tests/pck/cord/187.0001.json, tests/pck/cord/187.0002.dependent_ecommerce_questions.json, tests/pck/cord/187.0002.json, transform/transformers/cord/ecommerce_transformer.py
The apostrophe eq was sending was the unexpected kind (a regular one instead of a smart quote which is what we thought it was going to be)
=> Fix r2 transformation for 495

tests/transform/transformers/test_cord_formatter.py, transform/transformers/cord/cord_formatter.py
> Seems that the original requirement to prefix any 4 digit period with a "20" was incorrect. In the case of E-commerce a "12" needs to be post-fixed to any 4 digit period.
=> fix for ecommerce receipt
