ONSdigital/sdx-transform-cs

- transform/views/main.py
- transform/views/test_views.py
- transformers/CSTransformer.py
- transformers/ImageTransformer.py
- transformers/PDFTransformer.py
**Changes**
Where possible, create temporary files in memory to keep temp dirs clear:
- Create zips in memory
- Move buffer logic for pdf into transformer
- Completely remove temporary trees
- Run unit tests and check they pass. 
- Start a local server and call the /cs-test endpoint or post a json survey response to /common-software. 
- Check that the ./tmp directory has been cleared down after a request is made and is empty
> Create temp files in memory

- Dockerfile
- server.py
- settings.py
**Changes**
- Remove the handler logging to file
- Remove log file directory creation from dockerfile
Start the app as part of compose setup. Check that logging continues to stdout (terminal from compose), check that log files are no created anywhere.
Anyone but @iwootten
> Remove log handler

- surveys/023.0102.json
- surveys/023.0112.json
- surveys/023.0203.json
- surveys/023.0205.json
- surveys/023.0213.json
- surveys/023.0215.json
**Changes**
Add section headings/missing titles to copy in survey templates.
Check that json looks legitimate.
Anyone but @iwootten
> Add section numbers to headings

- transform/transformers/PDFTransformer.py
**Changes**
Allow a question to have no answer on PDF output.
- Submit a survey with no comment (question id 146)
- Verify the image files are generated successfully
Anyone but @ajmaddaford
> Update PDF render to allow questions to have no answer

- transform/surveys/023.0102.json
The comments block was missing from the JSON config meaning that
the comments weren't being output on the image and the PCK file
was missing the line for question 146.
> Add comments block to JSON config for survey 0112

- transform/settings.py
- transform/templates/csv.tmpl
- transform/transformers/ImageTransformer.py
**Changes**
- Use an environment variable for image paths. Use a better name.
- Start in compose, using an environment variable SDX_FTP_IMAGES_PATH within sdx-transform-cs setup set to a custom value
- Check files are created as expected and csv content uses custom path value
Anyone but @iwootten
> Sdx ftp image path

- transform/transformers/CSTransformer.py
- transform/transformers/ImageTransformer.py
Run `make test` to see the new logging lines. Be aware that output could increase significantly.
> Add new logging to identify image, pck and idbr file paths

- CHANGELOG.md
- transform/transformers/MWSSTransformer.py
- transform/transformers/PDFTransformer.py
Porting the changes from https://github.com/ONSdigital/sdx-transform-cora/pull/22
> Image changes - Red text for answers

- CHANGELOG.md
- requirements.txt
* Pinned version 1.7.0 of sdx-common
> Pinned version 1.7.0 of sdx-common (#84)

- tests/test_mwss_transform.py
> What does this pull request change/fix? Why was it nessessary?
Added a test to make sure decimals are being handled correctly.
> Added test for handling decimals

- tests/test_mwss_transform.py
Reformats the unit tests that were broken following the move to github flow
> Fix unit tests after moving to github flow

- transform/transformers/PDFTransformer.py
> Cast answers to string

- CHANGELOG.md
- requirements.txt
> Update sdx-common version

- CHANGELOG.md
- transform/__init__.py
> Update changelog and version number

- CHANGELOG.md
- Dockerfile
> Fix issues with Cryptography install and install correct requirements

- CHANGELOG.md
- transform/__init__.py
> Update chnagelog and version number

- .gitignore
- CHANGELOG.md
- requirements.txt
- tests/replies/eq-mwss.json
- tests/test_mwss_transform.py
- transform/transformers/MWSSTransformer.py
Implements changes to the `MWSSTransformer` module to support decimals in currency fields.
> Handle decimals mwss currency questions

- .gitignore
- CHANGELOG.md
- requirements.txt
- tests/replies/eq-mwss.json
- tests/test_cs_transform.py
- tests/test_mwss_transform.py
- tests/test_pdf_transform.py
- tests/test_transform.py
- transform/__init__.py
- transform/transformers/CSTransformer.py
- transform/transformers/ImageTransformer.py
- transform/transformers/MWSSTransformer.py
- transform/transformers/PDFTransformer.py
- transform/transformers/__init__.py
- transform/views/main.py
- transform/views/test_views.py
> Reverting the move to SDX common because the common library does not work correctly
> Reverting changes to move to sdx common

- .gitignore
- CHANGELOG.md
- requirements.txt
- tests/replies/eq-mwss.json
- tests/test_mwss_transform.py
- transform/transformers/ImageTransformer.py
- transform/transformers/MWSSTransformer.py
> Support for decimals in MWSS currency fields
> Mwss decimals

- CHANGELOG.md
- transform/__init__.py
> Update release version

- CHANGELOG.md
- transform/__init__.py
> Update version number

- CHANGELOG.md
- config.ini
- transform/__init__.py
- transform/settings.py
- transform/transformers/ImageTransformer.py
Add all gitlab and github config for the service to config file. Having all the config in one place should make changes easier.
> Add config file

- CHANGELOG.md
- transform/surveys/023.0112.json
- transform/surveys/023.0203.json
- transform/surveys/023.0205.json
- transform/surveys/023.0213.json
- transform/surveys/023.0215.json
Mend spelling mistake in RSI image.
> Fix spelling mistake in image

- Dockerfile
> Remove unnecessary steps from the dockerfile

- CHANGELOG.md
- transform/__init__.py
Fix incorrect image index date time
> Release 2.12.0

- CHANGELOG.md
- transform/__init__.py
> release version 2.13.0

- multi-buildpack.yml
Correcting the python build pack in multi build pack
> Use github python build pack

- CHANGELOG.md
- manifest.yml
- transform/views/main.py
> Add /info healthcheck endpoint

- CHANGELOG.md
- transform/__init__.py
Updating repo for release 3.3.0
> Release v3.3.0

- CHANGELOG.md
- transform/__init__.py
Release for v3.4.0 MBS transform
> Update version and change log for release 3.4.0

- CHANGELOG.md
- tests/test_mbs_transformer.py
- transform/transformers/mbs_transformer.py
> Fixes issue with q_code displaying default data
> Change d40 q code to d49

- CHANGELOG.md
- transform/__init__.py
> Update changelog and version

- CHANGELOG.md
- tests/test_mbs_transformer.py
- transform/transformers/mbs_transformer.py
- Fixes an error where rounding was coming through incorrectly. 
- 1234500 Should come through as 1235, but came through as 1234
> Fix rounding error based on thousand(s) 500

- tests/test_pck_transformer.py
- transform/surveys/019.0018.json
- transform/surveys/019.0019.json
- transform/surveys/019.0020.json
- transform/transformers/pck_transformer.py
Added support for QCAS survey.
Test on sdx-console and ensure that the:
1. Data from eq submits successfully.
2. PCKs are valid. https://docs.google.com/spreadsheets/d/1DSLtru61W7F27K7tWZjsfMHJFN5kpcpS4qNsHy30LEY/edit#gid=108466985 
3. Images are as expected.
> QCAS Support

- CHANGELOG.md
- tests/test_mbs_transformer.py
- transform/transformers/mbs_transformer.py
- There was an issue with one of the periods (INC0089761 for reference), this is just adding more tests for extra security on our side
- Adding these showed 1 or 2 things that either weren't working or weren't being used
> Add more tests for MBS transformer

- CHANGELOG.md
- transform/surveys/017.0001.json
- transform/surveys/017.0002.json
Fixes a small issue in the stocks questions. Reopened pull request to add signing
> Update stocks formtypes to fix question

- CHANGELOG.md
- transform/__init__.py
> Updated changelog and version

- CHANGELOG.md
- transform/__init__.py
> 3.12.2 release
- [ x] CHANGELOG.md updated? (if required)
> 3.12.2 Release

- transform/surveys/187.0001.json
- transform/surveys/187.0002.json
> Add missing comments to images for ecommerce 2019

- CHANGELOG.md
- transform/__init__.py
E Commerce bug fixes 
https://trello.com/c/p8v0ZPSQ
- [x ] CHANGELOG.md updated? (if required)
> Release 3.13.1

- CHANGELOG.md
- transform/__init__.py
Release for construction transformation fix
> Release 3.17.0

- CHANGELOG.md
- transform/__init__.py
> version 3.17.1

- CHANGELOG.md
- transform/__init__.py
> update version number to 3.18.0

- README.md
> add missing info to Readme

- CHANGELOG.md
- transform/__init__.py
> update release number to 3.19.0

- CHANGELOG.md
- tests/transform/transformers/test_cs_formatter.py
- transform/utilities/formatter.py
> Ensure that all IDBR receipts have a 6 digit period
> 6digit receipts

- transform/transformers/cord/cord_formatter.py
>Updated comment on CORD formatting for IDBR
> updated comment

- CHANGELOG.md
- transform/__init__.py
> update version number to 3.20.0

- CHANGELOG.md
- tests/transform/transformers/test_cord_formatter.py
- transform/transformers/cord/cord_formatter.py
- transform/transformers/cord/ecommerce_transformer.py
> Fixes the period within the index.csv for e-commerce surveys
> Fix E-commerce index file period

- CHANGELOG.md
- transform/__init__.py
> update version to 3.21.0

- CHANGELOG.md
- server.py
- transform/__init__.py
> Moved logging setup so that it is within scope for gunicorn startup
> Moved logging setup

- CHANGELOG.md
- transform/__init__.py
> Release 4.0.0

- CHANGELOG.md
- transform/__init__.py
> release 4.1.0

- CHANGELOG.md
- transform/__init__.py
> release 4.3.0

- CHANGELOG.md
- transform/__init__.py
> Release 4.3.1

- .gitignore
- CHANGELOG.md
- pyvenv.cfg
- transform/surveys/007.0009.json
- transform/surveys/007.0010.json
- transform/transformers/common_software/low_carbon_transformer.py
- transform/transformers/transform_selector.py
> Adding low carbon survey into transform (007) and generating the image files
- yes
> Low carbon

- CHANGELOG.md
- transform/__init__.py
> release 4.4.0

- _helm/sdx-transform/Chart.yaml
- _helm/sdx-transform/templates/deployment.yaml
- _helm/sdx-transform/templates/service.yaml
- _helm/sdx-transform/values.yaml
> helm directory

- Dockerfile
- _helm/sdx-transform/Chart.yaml
- _helm/sdx-transform/templates/deployment.yaml
- run.py
Run using gunicorn. Kubernetes liveness probe.
> Wsgi server

- CHANGELOG.md
- transform/__init__.py
> release 4.5.0
